#ifndef _DA_DEFINE_NULL_COMMANDS_
  #define _DA_DEFINE_NULL_COMMANDS_
/* COMANDOS DE TRANSMISION VACIOS */
/**********************************/



	#define Comando_00     CMD_NULL
    #define Comando_01     CMD_NULL
    #define Comando_02     CMD_NULL
    #define Comando_03     CMD_NULL
    #define Comando_04     CMD_NULL
    #define Comando_05     CMD_NULL
    #define Comando_06     CMD_NULL
    #define Comando_07     CMD_NULL
    #define Comando_08     CMD_NULL
    #define Comando_09     CMD_NULL
    #define Comando_0A     CMD_NULL
    #define Comando_0B     CMD_NULL
    #define Comando_0C     CMD_NULL
    #define Comando_0D     CMD_NULL
    #define Comando_0E     CMD_NULL
    #define Comando_0F     CMD_NULL

    #define Comando_10     CMD_NULL
    #define Comando_11     CMD_NULL
    #define Comando_12     CMD_NULL
    #define Comando_13     CMD_NULL
    #define Comando_14     CMD_NULL
    #define Comando_15     CMD_NULL
    #define Comando_16     CMD_NULL
    #define Comando_17     CMD_NULL
    #define Comando_18     CMD_NULL
    #define Comando_19     CMD_NULL
    #define Comando_1A     CMD_NULL
    #define Comando_1B     CMD_NULL
    #define Comando_1C     CMD_NULL
    #define Comando_1D     CMD_NULL
    #define Comando_1E     CMD_NULL
    #define Comando_1F     CMD_NULL

    #define Comando_20     CMD_NULL
    #define Comando_21     CMD_NULL
    #define Comando_22     CMD_NULL
    #define Comando_23     CMD_NULL
    #define Comando_24     CMD_NULL
    #define Comando_25     CMD_NULL
    #define Comando_26     CMD_NULL
    #define Comando_27     CMD_NULL
    #define Comando_28     CMD_NULL
    #define Comando_29     CMD_NULL
    #define Comando_2A     CMD_NULL
    #define Comando_2B     CMD_NULL
    #define Comando_2C     CMD_NULL
    #define Comando_2D     CMD_NULL
    #define Comando_2E     CMD_NULL
    #define Comando_2F     CMD_NULL

    #define Comando_30     CMD_NULL
    #define Comando_31     CMD_NULL
    #define Comando_32     CMD_NULL
    #define Comando_33     CMD_NULL
    #define Comando_34     CMD_NULL
    #define Comando_35     CMD_NULL
    #define Comando_36     CMD_NULL
    #define Comando_37     CMD_NULL
    #define Comando_38     CMD_NULL
    #define Comando_39     CMD_NULL
    #define Comando_3A     CMD_NULL
    #define Comando_3B     CMD_NULL
    #define Comando_3C     CMD_NULL
    #define Comando_3D     CMD_NULL
    #define Comando_3E     CMD_NULL
    #define Comando_3F     CMD_NULL

    #define Comando_40     CMD_NULL
    #define Comando_41     CMD_NULL
    #define Comando_42     CMD_NULL
    #define Comando_43     CMD_NULL
    #define Comando_44     CMD_NULL
    #define Comando_45     CMD_NULL
    #define Comando_46     CMD_NULL
    #define Comando_47     CMD_NULL
    #define Comando_48     CMD_NULL
    #define Comando_49     CMD_NULL
    #define Comando_4A     CMD_NULL
    #define Comando_4B     CMD_NULL
    #define Comando_4C     CMD_NULL
    #define Comando_4D     CMD_NULL
    #define Comando_4E     CMD_NULL
    #define Comando_4F     CMD_NULL

    #define Comando_50     CMD_NULL
    #define Comando_51     CMD_NULL
    #define Comando_52     CMD_NULL
    #define Comando_53     CMD_NULL
    #define Comando_54     CMD_NULL
    #define Comando_55     CMD_NULL
    #define Comando_56     CMD_NULL
    #define Comando_57     CMD_NULL
    #define Comando_58     CMD_NULL
    #define Comando_59     CMD_NULL
    #define Comando_5A     CMD_NULL
    #define Comando_5B     CMD_NULL
    #define Comando_5C     CMD_NULL
    #define Comando_5D     CMD_NULL
    #define Comando_5E     CMD_NULL
    #define Comando_5F     CMD_NULL

    #define Comando_60     CMD_NULL
    #define Comando_61     CMD_NULL
    #define Comando_62     CMD_NULL
    #define Comando_63     CMD_NULL
    #define Comando_64     CMD_NULL
    #define Comando_65     CMD_NULL
    #define Comando_66     CMD_NULL
    #define Comando_67     CMD_NULL
    #define Comando_68     CMD_NULL
    #define Comando_69     CMD_NULL
    #define Comando_6A     CMD_NULL
    #define Comando_6B     CMD_NULL
    #define Comando_6C     CMD_NULL
    #define Comando_6D     CMD_NULL
    #define Comando_6E     CMD_NULL
    #define Comando_6F     CMD_NULL

    #define Comando_70     CMD_NULL
    #define Comando_71     CMD_NULL
    #define Comando_72     CMD_NULL
    #define Comando_73     CMD_NULL
    #define Comando_74     CMD_NULL
    #define Comando_75     CMD_NULL
    #define Comando_76     CMD_NULL
    #define Comando_77     CMD_NULL
    #define Comando_78     CMD_NULL
    #define Comando_79     CMD_NULL
    #define Comando_7A     CMD_NULL
    #define Comando_7B     CMD_NULL
    #define Comando_7C     CMD_NULL
    #define Comando_7D     CMD_NULL
    #define Comando_7E     CMD_NULL
    #define Comando_7F     CMD_NULL


  /* FUNCIONES DE TRANSMISION VACIAS */
  /**********************************/
    #define Tx_comando_00     Tx_NONE
    #define Tx_comando_01     Tx_NONE
    #define Tx_comando_02     Tx_NONE
    #define Tx_comando_03     Tx_NONE
    #define Tx_comando_04     Tx_NONE
    #define Tx_comando_05     Tx_NONE
    #define Tx_comando_06     Tx_NONE
    #define Tx_comando_07     Tx_NONE
    #define Tx_comando_08     Tx_NONE
    #define Tx_comando_09     Tx_NONE
    #define Tx_comando_0A     Tx_NONE
    #define Tx_comando_0B     Tx_NONE
    #define Tx_comando_0C     Tx_NONE
    #define Tx_comando_0D     Tx_NONE
    #define Tx_comando_0E     Tx_NONE
    #define Tx_comando_0F     Tx_NONE

    #define Tx_comando_10     Tx_NONE
    #define Tx_comando_11     Tx_NONE
    #define Tx_comando_12     Tx_NONE
    #define Tx_comando_13     Tx_NONE
    #define Tx_comando_14     Tx_NONE
    #define Tx_comando_15     Tx_NONE
    #define Tx_comando_16     Tx_NONE
    #define Tx_comando_17     Tx_NONE
    #define Tx_comando_18     Tx_NONE
    #define Tx_comando_19     Tx_NONE
    #define Tx_comando_1A     Tx_NONE
    #define Tx_comando_1B     Tx_NONE
    #define Tx_comando_1C     Tx_NONE
    #define Tx_comando_1D     Tx_NONE
    #define Tx_comando_1E     Tx_NONE
    #define Tx_comando_1F     Tx_NONE

    #define Tx_comando_20     Tx_NONE
    #define Tx_comando_21     Tx_NONE
    #define Tx_comando_22     Tx_NONE
    #define Tx_comando_23     Tx_NONE
    #define Tx_comando_24     Tx_NONE
    #define Tx_comando_25     Tx_NONE
    #define Tx_comando_26     Tx_NONE
    #define Tx_comando_27     Tx_NONE
    #define Tx_comando_28     Tx_NONE
    #define Tx_comando_29     Tx_NONE
    #define Tx_comando_2A     Tx_NONE
    #define Tx_comando_2B     Tx_NONE
    #define Tx_comando_2C     Tx_NONE
    #define Tx_comando_2D     Tx_NONE
    #define Tx_comando_2E     Tx_NONE
    #define Tx_comando_2F     Tx_NONE

    #define Tx_comando_30     Tx_NONE
    #define Tx_comando_31     Tx_NONE
    #define Tx_comando_32     Tx_NONE
    #define Tx_comando_33     Tx_NONE
    #define Tx_comando_34     Tx_NONE
    #define Tx_comando_35     Tx_NONE
    #define Tx_comando_36     Tx_NONE
    #define Tx_comando_37     Tx_NONE
    #define Tx_comando_38     Tx_NONE
    #define Tx_comando_39     Tx_NONE
    #define Tx_comando_3A     Tx_NONE
    #define Tx_comando_3B     Tx_NONE
    #define Tx_comando_3C     Tx_NONE
    #define Tx_comando_3D     Tx_NONE
    #define Tx_comando_3E     Tx_NONE
    #define Tx_comando_3F     Tx_NONE

    #define Tx_comando_40     Tx_NONE
    #define Tx_comando_41     Tx_NONE
    #define Tx_comando_42     Tx_NONE
    #define Tx_comando_43     Tx_NONE
    #define Tx_comando_44     Tx_NONE
    #define Tx_comando_45     Tx_NONE
    #define Tx_comando_46     Tx_NONE
    #define Tx_comando_47     Tx_NONE
    #define Tx_comando_48     Tx_NONE
    #define Tx_comando_49     Tx_NONE
    #define Tx_comando_4A     Tx_NONE
    #define Tx_comando_4B     Tx_NONE
    #define Tx_comando_4C     Tx_NONE
    #define Tx_comando_4D     Tx_NONE
    #define Tx_comando_4E     Tx_NONE
    #define Tx_comando_4F     Tx_NONE

    #define Tx_comando_50     Tx_NONE
    #define Tx_comando_51     Tx_NONE
    #define Tx_comando_52     Tx_NONE
    #define Tx_comando_53     Tx_NONE
    #define Tx_comando_54     Tx_NONE
    #define Tx_comando_55     Tx_NONE
    #define Tx_comando_56     Tx_NONE
    #define Tx_comando_57     Tx_NONE
    #define Tx_comando_58     Tx_NONE
    #define Tx_comando_59     Tx_NONE
    #define Tx_comando_5A     Tx_NONE
    #define Tx_comando_5B     Tx_NONE
    #define Tx_comando_5C     Tx_NONE
    #define Tx_comando_5D     Tx_NONE
    #define Tx_comando_5E     Tx_NONE
    #define Tx_comando_5F     Tx_NONE

    #define Tx_comando_60     Tx_NONE
    #define Tx_comando_61     Tx_NONE
    #define Tx_comando_62     Tx_NONE
    #define Tx_comando_63     Tx_NONE
    #define Tx_comando_64     Tx_NONE
    #define Tx_comando_65     Tx_NONE
    #define Tx_comando_66     Tx_NONE
    #define Tx_comando_67     Tx_NONE
    #define Tx_comando_68     Tx_NONE
    #define Tx_comando_69     Tx_NONE
    #define Tx_comando_6A     Tx_NONE
    #define Tx_comando_6B     Tx_NONE
    #define Tx_comando_6C     Tx_NONE
    #define Tx_comando_6D     Tx_NONE
    #define Tx_comando_6E     Tx_NONE
    #define Tx_comando_6F     Tx_NONE

    #define Tx_comando_70     Tx_NONE
    #define Tx_comando_71     Tx_NONE
    #define Tx_comando_72     Tx_NONE
    #define Tx_comando_73     Tx_NONE
    #define Tx_comando_74     Tx_NONE
    #define Tx_comando_75     Tx_NONE
    #define Tx_comando_76     Tx_NONE
    #define Tx_comando_77     Tx_NONE
    #define Tx_comando_78     Tx_NONE
    #define Tx_comando_79     Tx_NONE
    #define Tx_comando_7A     Tx_NONE
    #define Tx_comando_7B     Tx_NONE
    #define Tx_comando_7C     Tx_NONE
    #define Tx_comando_7D     Tx_NONE
    #define Tx_comando_7E     Tx_NONE
    #define Tx_comando_7F     Tx_NONE

#endif
